# Generated by Django 4.2.4 on 2023-08-18 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.IntegerField()),
                ('personal_title', models.TextField(blank=True, choices=[('MR', 'Mister'), ('MS', 'Miss')], default=None)),
                ('date_of_birth', models.DateField()),
                ('disability', models.BooleanField()),
                ('residential_address', models.CharField(max_length=255)),
                ('residential_city', models.CharField(max_length=50)),
                ('residential_postal_code', models.CharField(max_length=10)),
                ('residential_phone', models.PositiveIntegerField()),
                ('personal_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
