# Generated by Django 4.2.4 on 2023-08-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_personal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personal_title',
            field=models.CharField(blank=True, choices=[('MR', 'Mister'), ('MS', 'Miss')], default=None, max_length=2),
        ),
    ]
