# Generated by Django 4.2.4 on 2023-08-19 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_supervisor_employee_gender_employee_marital_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employees_managed',
            field=models.ManyToManyField(related_name='managers', through='employee.Supervisor', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='from_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_employee', to='employee.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='to_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_employee', to='employee.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='residential_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='supervisor',
            unique_together={('from_employee', 'to_employee')},
        ),
    ]
