# Generated by Django 4.2.4 on 2023-08-19 17:55

from django.db import migrations, models
import django_countries.fields
import django_fsm
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('marked_as_joiner', 'Marked as Joiner'), ('future_joiner', 'Future Joiner'), ('active', 'Active'), ('marked_as_leaver', 'Marked as Leaver'), ('future_leaver', 'Future Leaver'), ('inactive', 'Inactive')], default='draft', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('PARTNERSHIP', 'Partnership')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_title',
            field=models.CharField(blank=True, choices=[('MR', 'Mister'), ('MS', 'Miss')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='residential_country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='residential_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='residential_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(choices=[('INT', 'Internal')], default='INT', max_length=3),
        ),
    ]
