# Generated by Django 4.2.4 on 2023-08-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employee_uuid_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='active',
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '---------'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('', '---------'), ('MARRIED', 'Married'), ('SINGLE', 'Single'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('PARTNERSHIP', 'Partnership')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_title',
            field=models.CharField(blank=True, choices=[('', '---------'), ('MR', 'Mister'), ('MS', 'Miss')], default=None, max_length=2, null=True),
        ),
    ]
