# Generated by Django 4.2.4 on 2023-08-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_remove_employee_active_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='type',
            new_name='supervisor_type',
        ),
    ]
