# Generated by Django 4.2.4 on 2023-08-22 21:24

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_rename_type_supervisor_supervisor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(max_length=25)),
                ('company', models.CharField(choices=[('JUMIA', 'Jumia')], default='JUMIA', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('probation_period', models.CharField(choices=[('NA', 'N/A'), ('15D', '15 Days'), ('30D', '30 Days'), ('60D', '60 Days')], default='NA', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contract_category', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legal_entity', models.CharField(max_length=10)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('annual_basic_salary', models.PositiveIntegerField(max_length=10)),
                ('currency_code', models.CharField(max_length=10)),
                ('effective_date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entitlements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(max_length=10)),
                ('include_in_salary', models.BooleanField(default=False)),
                ('net_or_gross', models.CharField(choices=[('N', 'NET'), ('G', 'GROSS')], max_length=1)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.salary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contract_type', models.CharField(max_length=10)),
                ('contract_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.contractcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.contracttype'),
        ),
        migrations.AddField(
            model_name='contract',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.legalentity'),
        ),
    ]
