# Generated by Django 4.2.4 on 2023-08-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_contract_contractcategory_legalentity_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlements',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='annual_basic_salary',
            field=models.PositiveIntegerField(),
        ),
    ]
