# Generated by Django 4.2.4 on 2023-08-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_entitlements_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='employee.employee'),
            preserve_default=False,
        ),
    ]
